server:
  http:
    addr: 0.0.0.0:28000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:29000
    timeout: 1s
  auto_run: true  # 是否在根命令下自动运行服务
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
